Change namespace from App to Oljn
Update all src files
Update autoload in composer.json
run composer dump-autoload

Error still occurs:
Fatal error: Cannot declare class Oljn\Card\Card,
because the name is already in use in
/home/lohengrin/dbwebb-kurser/mvc/me/report/src/Card/Card.php on line 10